name = "bh"
license = "Apache 2.0"
licenselink = "https://github.com/hspak/blog.hspak.com/blob/master/LICENSE"
description = ""
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Hong Shick Pak"
  homepage = "https://hspak.com"
